### ISSUE TITLE
   hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by thanhchinh** [josebenitezg/yolov8-streamlit-app#1]
2023-02-21 13:56:13.169 Uncaught app exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov8s\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\yolov8-streamlit-app-main\main.py", line 53, in <module>
    print(subprocess.run(['yolo', 'task=detect', 'mode=predict', 'model=yolov8n.pt', 'conf=0.25', 'source={}'.format(source)],capture_output=True, universal_newlines=True).stderr)
  File "C:\ProgramData\Anaconda3\envs\yolov8s\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\envs\yolov8s\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\envs\yolov8s\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Plezzz

**Comment by josebenitezg** [comment]
Hi @thanhchinh Might be an issue with the working directory. Have you installed yolov8 properly?

**Comment by thanhchinh** [comment]
i pip install ultralytics, maybe error from different version?

**Comment by thanhchinh** [comment]
@josebenitezg thank for reply

**Comment by josebenitezg** [comment]
Have you tried yo run the yolov8 cli in your terminal? It seems you are running on windows

**Comment by thanhchinh** [comment]
ultralytics 0.0.13 depends on torch>=1.7.0
    torchvision 0.9.1 depends on torch==1.8.1
    The user requested torch==1.7.1
    ultralytics 0.0.13 depends on torch>=1.7.0
    torchvision 0.9.0 depends on torch==1.8.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
